### ISSUE TITLE
ReflectionAlpha

### ISSUE THREAD

**Issue by natemac** [phulshof/RetroFE#3] opened 2021-04-12 15:26 UTC
0.10.20 Menu Image Reflection Alpha
0, 0.1 or 0.9 always shows the reflection at 100% alpha (opaque). values have no effect.
`	<menu mode="system" type="custom" imageType="cover" scrollTime=".30" scrollAcceleration=".05" minScrollTime=".20" orientation="horizontal">
  <itemDefaults x="center" y="center"  xOrigin="center" yOrigin="center" alpha="1" width="232" spacing="10" reflectionDistance="8" reflection="bottom" reflectionScale="1" reflectionAlpha="0.1" layer="15"/>
    <item xOffset="-577" alpha="0"  width="122" layer="11" angle="0"/>`

**Comment by John-Smith-UK** [comment] 2021-04-12 16:43
I second the above. Regardless of the alpha value set, it shows as if alpha has been set as 1

**Comment by phulshof** [comment] 2021-04-13 10:57
This is by design. Reflection is always relative to the original, because an invisible object has no reflection. As such, the alpha value for the reflection is the multiplication of the configured alpha values for the original and the reflection.

**Comment by John-Smith-UK** [comment] 2021-04-13 10:59
You're missing the point, The alpha of the REFLECTION is 1 regardless if its set to less than 1. Even if I have the original items alpha set to 1, and set the reflective alpha to half of that (0.5), the reflection still outputs as 1.

**Comment by phulshof** [comment] 2021-04-13 11:01
I will test it, but as far as I recall I fixed that a few releases ago. Should it require additional fixes however, I'll add them to the next release.

**Comment by John-Smith-UK** [comment] 2021-04-13 11:02
Then must be when it was broken as it worked fine in 0.10.7

**Comment by phulshof** [comment] 2021-04-13 11:04
I broke it when I added multiple reflection directions; as far as I know I fixed it afterwards, but perhaps something went wrong when I checked in the new code. Developing on both Windows and Linux sometimes causes me to make mistakes.

**Comment by phulshof** [comment] 2021-04-13 11:08
I had a quick look at the code. It seems I broke it again when I added the rotation and mirror mode code. I'll make note of it, and fix it asap.

**Comment by John-Smith-UK** [comment] 2021-04-13 11:09
Thanks.

**Comment by phulshof** [comment] 2021-04-13 14:02
I've already reproduced and fixed the bug locally. I'm currently implementing the playlist menu structure, so once that' s complete I'll check in the code, and make a new release.

**Comment by phulshof** [comment] 2021-05-05 09:22
The playlist menu structure is taking a bit longer than I anticipated, so I just fixed the reflection bug in the code.

**Closed** 2023-04-19 09:22 UTC
